### PR TITLE
Set up typescript for backend

### PR DESCRIPTION
**Pull request by SeanEZhou**
- converted all javascript files to typescript, making necessary changes to code
- added typescript to package dependency
- corrected ill-formatted tests
- setup eslint to use a typescript parser

### CODE REVIEW

**Review by khushi02 — APPROVED** [review]
Great work, Sean! Thanks for normalizing the schemas, I think this looks ready to go.

**Review by McSobkov — CHANGES_REQUESTED** [review]
The only comment is that we should put the tests in a schema subfolder, given that we'll probably have a bunch of test files, it'll help with organization.

**Comment by SeanEZhou** [comment]
> The only comment is that we should put the tests in a schema subfolder, given that we'll probably have a bunch of test files, it'll help with organization.

I’d say we do that when we actually get more tests. Doing this now unnecessarily complicates our project structure.

**Review by phi-h-nguyen — APPROVED** [review]
Looks good to me! I'm pretty ambivalent about the test project structure right now, since it's a two-way door decision that won't have much effect on future development and it can be easily changed either way

**Pull request merged**
