### PR TITLE
Added address input and button to checkout with state

### PR DESCRIPTION
**Pull request by phi-h-nguyen**

### CODE REVIEW

**Review by McSobkov — APPROVED** [review]
Are the console.logs in Order.tsx remnants of debugging or are they supposed to stay there?

**Review by khushi02 — COMMENTED** [review]
Hey Phi, great work on the menu page updates! Since we are already getting the delivery address and calculating the estimated time on the checkout page, I think we can remove it from the menu page.

**Comment by phi-h-nguyen** [comment]
Thanks for the feedback!  Added two more commits removing the delivery address and I also replaced "Shipping" with "Delivery" to be consistent with our MVP video

**Review by khushi02 — APPROVED** [review]
looks good!

**Pull request merged**
