### PR TITLE
Updated menu page with real items, pulled from a menu.tsx file

### PR DESCRIPTION
**Pull request by phi-h-nguyen**
Imported all images for donuts and updated menu page to pull in data from a separate file

### CODE REVIEW

**Review by SeanEZhou — APPROVED** [review]
Looks great Phi! Good work on setting up the static menu, that should make it easy to map item ids to item information

**Review by khushi02 — APPROVED** [review]
This looks good to me. Great work!

**Review by McSobkov — COMMENTED** [review]
May be worth adding ids to the donuts in the menu.tsx file to match the ODM. I like the idea of including the pics in the database. If you want to add those to the ODM, I can update it on the backend, so that if we get around to building that data pipeline, it will be an easier transition.

**Comment by SeanEZhou** [comment]
Do you mean to use the array index of the item as id? I think that would work well, as we can find a particular item by indexing rather than looping over the array and checking id one by one

**Pull request merged**
