### PR TITLE
initial order page

### PR DESCRIPTION
**Pull request by khushi02**

### CODE REVIEW

**Review by SeanEZhou — APPROVED** [review]
Hi Khushi thanks for the PR! I think this is a good template for building our dronuts specific order summary. Good work!

**Review by phi-h-nguyen — COMMENTED** [review]
Yeah this looks really good! I don't think we have to change it to make it look like doordash, this looks completely fine to me! I think the only thing I'd change is moving the components (like the forms) into the components folder

**Review by McSobkov — APPROVED** [review]
Yea, I have nothing to add. Looks solid!

**Review by phi-h-nguyen — APPROVED** [review]
Looks great, thanks for the changes Khushi!

**Pull request merged**
