### PR TITLE
Get donut inventory

### PR DESCRIPTION
**Pull request by McSobkov**

### CODE REVIEW

**Comment by phi-h-nguyen** [comment]
Will routes for updating the donuts inventory be in another PR? If so, then this looks good for just pulling the menu from the backend!

**Review by khushi02 — APPROVED** [review]
Hey Max, great work! Same question as Phi, otherwise it looks good to me.

**Comment by McSobkov** [comment]
> Will routes for updating the donuts inventory be in another PR? If so, then this looks good for just pulling the menu from the backend!

Yep, that's the next one I'm working on

**Review by phi-h-nguyen — APPROVED** [review]
lgtm!

**Pull request merged**
